Working branch
Maryjanee/Bubble-Sort pull request #2
Opened 2020-07-16 10:00 UTC by Maryjanee

### Project Description

- Implemented the bubble sort algorithm by creating a method called bubble_sort
- Implemented the bubble sort by algorithm by creating a method called bubble_sort_by using yield.

2020-07-16 21:39 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Let's work on the readme.MD file (The usage section).
- [x] The methods `bubble_sort` & `bubble_sort_by`  should be in one file 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-17 13:01 UTC, santiago-dev96 approved these changes
# Project approved! :100:

Everything works fine, but your `README.md` still needs some work, I'll suggest implementing the changes requested as soon as possible, this is optional though, just some details.

I wish you the best for your next projects! 😄

2020-07-17 13:01 UTC, santiago-dev96 commented on README.md
> +This project consist of implementing the bubble sort algorithm with the ruby programming language.
Proper names are capitalized.
```suggestion
This project consists of implementing the bubble sort algorithm with the Ruby programming language. 
```

2020-07-17 13:01 UTC, santiago-dev96 commented on README.md
> +- Rubocop
This is not necessary.
```suggestion
```

2020-07-17 13:01 UTC, santiago-dev96 commented on README.md
> +## Built With
I suggest changing this to something more clear.
```suggestion
## Requirements
```

2020-07-17 13:01 UTC, santiago-dev96 commented on README.md
> +- Ruby
Try to specify the Ruby version you used for this project.
```suggestion
- Ruby (X.X.X)
```

2020-07-17 13:01 UTC, santiago-dev96 commented on README.md
> +$ git clone git@github.com:Maryjanee/Bubble-Sort.git
That's not the way you provide directions to issue commands on the terminal. Also, other users can't clone your repositories using SSH. Surround the following with three backticks and at the end of the opening backticks type **sh**.
```suggestion
git clone https://github.com/Maryjanee/Bubble-Sort.git
cd Bubble-Sort
```

2020-07-17 19:15 UTC, merged